[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[http.headers]
# --- 変更: 競合するContent-Security-Policyディレクティブを削除 ---
# CSPはserver.jsのhelmetミドルウェアによって管理されるようになります
"X-Frame-Options" = "DENY"
"X-Content-Type-Options" = "nosniff"
"Cross-Origin-Resource-Policy" = "same-site"