[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[http.headers]
# Эта политика разрешает все, что нужно вашему приложению, и ничего лишнего.
"Content-Security-Policy" = "default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://script.google.com https://script.googleusercontent.com; font-src 'self' https://fonts.gstatic.com;"
# Эти заголовки - стандартная хорошая практика для безопасности.
"X-Frame-Options" = "DENY"
"X-Content-Type-Options" = "nosniff"
# Этот заголовок важен, чтобы исправить ошибку с favicon.ico
"Cross-Origin-Resource-Policy" = "same-site"