version: '3'

vars:
  TSC: './node_modules/.bin/tsc'

tasks:
  build:
    cmds:
      - '{{.TSC}}'

  test:
    deps: [build]
    cmds:
      - node -r dotenv/config dist/index.js dotenv_config_path=local.env